### ISSUE TITLE
Removing the hashcode reference in the multiplay module

### ISSUE THREAD

**Issue by magmukendi** [JasperGame/zepeto-modules#52]
## Module

* [ ] Module Importer
* [X] Multiplay Component
* [ ] Interaction
* [ ] Gesture
* [ ] Screenshot
* [ ] Leaderboard
* [ ] Mannequin
* [ ] Product
* [ ] Localisation
* [ ] QuickChat

## Version
- Unity 2020.9.3f1
- Zepeto WORLD SDK 1.21.11 

## Describe the bug (actual behavior)
It's not a bug but the new multiplay module source does not include any hashcode reference anymore. There is need to make an update by removing that hashcode.

## Expected behavior
Multiplay module without mention of the hashcode.

### Unity 20209.3f1
- Version
  
### Zepeto World SDK
- Version

**Comment by magmukendi** [comment]
@bohyunjung I went through the index.ts file. I would your assistance here.

There is mention of hashcode from SandboxPlayer, did you mean to say the `SandboxPlayer` interface does not have any hashcode property anymore? Hence making obsolete the line that checks if the `client.hashcode` is identical to `player.zepetoHash`?

The picture below is for illustration. 
![image](https://github.com/JasperGame/zepeto-modules/assets/64711820/830d3264-5a13-4df1-9500-167589a10a1d)


If I understand well, after the changes, we will not need to check if the `client.hashcode` is true and only check if the `client.userId` is true.


I also checked the documentation and it seems like the hashcode from the SandboxPlayer interface is still mentioned in the `onJoin` method, do you think that those two mentions need to be updated as well?

![image](https://github.com/JasperGame/zepeto-modules/assets/64711820/4fae62a3-b72d-43f2-a49a-48f04033f17a)
![image](https://github.com/JasperGame/zepeto-modules/assets/64711820/51c0e418-781a-49ed-8868-caa25c9b1a06)


Here are the links of the code in `index.ts` that still mention hashcode in the documentation:

- [Gesture](https://docs.zepeto.me/studio/reference/gesture#step-4-2--server-code)
- [Player synchronization](https://docs.zepeto.me/studio/reference/zepetoplayers#step-3-1--server-script-with-completed-position-synchronization)

**Comment by bohyunjung** [comment]
@magmukendi Thanks for the ping.

### 1

Yes, the `SandboxPlayer` interface has no `hashcode` in the recent releases.
Therefore, it is required to remove the codes referencing it since creators can update their ZEPETO Multiplay SDK after integrating the ZEPETO modules.

From this repo, I see the only part referencing it is [here](https://github.com/JasperGame/zepeto-modules/blob/44d691c73023690426cb1ac4aa6b2f84a90784d6/Project/zepeto-modules/Assets/World.multiplay/index.ts#L26-L28).

### 2

Plus, I think it is also worth removing the `zepetoHash` from the Multiplay schema.

---

If you could make these two changes above and make a release PR for the Multiplay Component, we'll handle the SDK document part. (Thanks for pointing that out.)

Updating the SDK to the newest SDK should also be needed, but that's beyond this issue's coverage.
